/*
 * Project name:
     MyProject.mcpar
 * Generated by:
     Visual TFT
 * Date of creation
     14.6.2024.
 * Test configuration:
     MCU:             MK64FN1M0XXX12
     Dev.Board:       Fusion_for_NXP_Board_5_Capacitive
     Oscillator:      120000000 Hz
     SW:              mikroC PRO for ARM
                      http://www.mikroe.com/mikroc/arm/
 */

#include "MyProject_objects.h"
#include "MyProject_events_code.h"



void main() {

  TFT_Rotate_180(1);
  Start_TP();

  while (1) {
  
    Check_TP();
        
  }
}